/// <reference types="cypress" />


describe('add new value', () => {
    beforeEach('login', () => {
        cy.visit('https://uatdataservices.gig.com.jo:84/')
        cy.Login('username', 'password')
        cy.get(':nth-child(6) > [href="#"]').click()
        cy.get('.active > .sidebar-submenu > ul > :nth-child(5) > a').click()
        cy.get('.table-title > .btn').click()

    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Hawaii')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Russia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Estonia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Latvia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Mali')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Finland')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Sierra Leone')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Argentina')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Austria')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Mauritania')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Malta')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('USA')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('India')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Afghanistan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Syria')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Qatar')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Rwanda')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Senegal')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Vatican City')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Yugoslavia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Zanzibar')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Monaco')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Botswana')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Ukraine')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Grenada/Carricou')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Panama')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Czech Republic')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Kazakhistan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Saudi Arabia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('ISRAEL')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Benin')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Ascension')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Canada')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Brunei Darussalm')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Burkina Faso')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Colombia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Congo (Brazzaville)')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Bahamas')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('San Tone and Principe')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Barbados')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Madagascar')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Antilles Island')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Burma')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Dominican Republic')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('East Timor')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Faroe Islands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Gabonese Republic')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Haiti')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Kuwait')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Luxembourg')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Central African Republic')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Tokelau')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Trinidad and Tobago')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Tunisia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Turkmenistan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Macedonia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Mauritius')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Morocco')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Nicaragua')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Mozambique')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Lebanon')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Greece')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Mexico')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Netherlands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Palestine')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('San Marino')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Suriname')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Zimbabwe')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Kirgizstan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Australia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })

    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Taiwan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })

    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Turkey')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Venezuela')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Zambia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Switzerland')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('American Samoa')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Andorra')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Brazil')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Armenia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Belarus')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Bosnia/Hercegovina')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Slovenia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Malawi')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Maldives')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Chad')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Djibouti')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('algeria')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Paraguay')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Peru')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Iceland')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Indonesia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Ireland')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Cyprus')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Hong Kong')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Italy')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('New Zealand')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Norway')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Philippines')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Poland')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Portugal')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Romania')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Singapore')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Slovakia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('South Korea')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Spain')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Sudan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Sweden')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Solomon Islands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Somalia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Sri Lanka')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Swaziland')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Tajikistan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Tanzania')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('United Arab Emirates')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('US Virgin Islands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Uruguay')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Uzbekistan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Vanuatu')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Vietnam')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Wallis and Futuna')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Libya')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Liechtenstein')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Lithuania')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Macao')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Puerto Rico')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Seychelles')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Slovenia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Belgium')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Bermuda')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Bulgaria')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('China')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Albania')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Angola')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Antigua/Barbuda')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Aruba')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Azerbaijan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Bahrain')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Belize')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Bhutan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Bolivia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('British Virgin Islands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Turks and Caicos')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Tuvalu')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Uganda')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Laos')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Lesotho')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Liberia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Martinique')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Micronesia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Moldova')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Mongolia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Montserrat')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('France')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Germany Deutsche')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Jamaica')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Japan')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Cook Islands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Croatia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Cuba')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Dominica')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Ecuador')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('El Salvador')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Equatorial Guinea')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Eritrea')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Ethiopia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Falkland Islands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('French Guiana')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('French Polynesia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Gambia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Georgia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Ghana')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Gibraltar')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Greenland')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Guam')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Guadeloupe')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Guatemala')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Guinea')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Guinea-Bissau')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Guyana')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Honduras')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Iraq')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Kenya')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Kiribati')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Hungary')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Namibia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Nauru')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Nepal')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('New Caledonia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Niger')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Nigeria')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Niue Island')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Oman')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Palau')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Palestine')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Papua New Guinea')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Netherlands Antilles')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Northern Mariana Islands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('United Kingdom')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Denmark')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Egypt')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Burundi')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Cambodia')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Cameroon')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()
    })
    it('add', () => {
        cy.get('#TRV_COVER_ID').select('2')
        cy.get('#CTRY_ID')
        cy.get('#CTRY_ID').select('Cayman Islands')
        cy.get('#RES_STATUS').select('A')
        cy.get('.save-btn').click()

    })

})